name: Node.js Package

on:
  push:
    branches:
      - main

jobs:
  publish-gpr:
    permissions: write-all
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v2
        with:
          node-version: 18
          registry-url: https://npm.pkg.github.com/
          scope: "@guiisn"
      - run: npm install -g pnpm
      - run: pnpm install --loglevel=error

      - name: Set git identity
        run: |
          git config user.email "glhrmsouzanunes@gmail.com"
          git config user.name "guiisn"

      - run: pnpm build # Adicione o comando pnpm build aqui
      - run: pnpm publish
        env:
          NODE_AUTH_TOKEN: ${{secrets.GITHUB_TOKEN}}
